#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "F1647D6A1C091A9B125DB1D50F828BF966A2F260E222D02522436BC30A14F653"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Tekla.Structures.Dialog;
using Tekla.Structures.Dialog.UIControls;
using TestWPFBeamPlugin;


namespace TestWPFBeamPlugin {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : Tekla.Structures.Dialog.PluginWindowBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 37 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label partNameLabel;
        
        #line default
        #line hidden
        
        
        #line 48 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox partNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 74 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_Copy;
        
        #line default
        #line hidden
        
        
        #line 80 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox_Copy;
        
        #line default
        #line hidden
        
        
        #line 87 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfProfileCatalog profileCatalog;
        
        #line default
        #line hidden
        
        
        #line 94 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_Copy1;
        
        #line default
        #line hidden
        
        
        #line 105 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox_Copy1;
        
        #line default
        #line hidden
        
        
        #line 115 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_Material;
        
        #line default
        #line hidden
        
        
        #line 126 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox materialBox;
        
        #line default
        #line hidden
        
        
        #line 133 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog materialCatalog;
        
        #line default
        #line hidden
        
        
        #line 145 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_component;
        
        #line default
        #line hidden
        
        
        #line 152 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox componentnameBox;
        
        #line default
        #line hidden
        
        
        #line 160 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox componentnumberBox;
        
        #line default
        #line hidden
        
        
        #line 167 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfComponentCatalog componentCatalog;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TestWPFBeamPlugin;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.partNameLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.partNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.label_Copy = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.textBox_Copy = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.profileCatalog = ((Tekla.Structures.Dialog.UIControls.WpfProfileCatalog)(target));
            
            #line 89 "MainWindow.xaml"
            this.profileCatalog.SelectClicked += new System.EventHandler(this.profileCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 90 "MainWindow.xaml"
            this.profileCatalog.SelectionDone += new System.EventHandler(this.profileCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 6:
            this.label_Copy1 = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.textBox_Copy1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.label_Material = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.materialBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.materialCatalog = ((Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog)(target));
            
            #line 137 "MainWindow.xaml"
            this.materialCatalog.SelectClicked += new System.EventHandler(this.WPFMaterialCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 138 "MainWindow.xaml"
            this.materialCatalog.SelectionDone += new System.EventHandler(this.WPFMaterialCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 11:
            this.label_component = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.componentnameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.componentnumberBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.componentCatalog = ((Tekla.Structures.Dialog.UIControls.WpfComponentCatalog)(target));
            
            #line 169 "MainWindow.xaml"
            this.componentCatalog.SelectClicked += new System.EventHandler(this.componentCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 170 "MainWindow.xaml"
            this.componentCatalog.SelectionDone += new System.EventHandler(this.componentCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 175 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ApplyClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_ApplyClicked);
            
            #line default
            #line hidden
            
            #line 176 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).CancelClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_CancelClicked);
            
            #line default
            #line hidden
            
            #line 177 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).GetClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_GetClicked);
            
            #line default
            #line hidden
            
            #line 178 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ModifyClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_ModifyClicked);
            
            #line default
            #line hidden
            
            #line 179 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OkClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_OkClicked);
            
            #line default
            #line hidden
            
            #line 180 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OnOffClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_OnOffClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

